{% set version = "0.9.1" %}

package:
  name: terminado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/terminado/terminado-{{ version }}.tar.gz
  sha256: 3da72a155b807b01c9e8a5babd214e052a0a45a975751da3521a1c3381ce6d76

build:
  number: 0
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - ptyprocess  # [not win]
    - pywinpty  # [win]
    - tornado >=4

test:
  imports:
    - terminado

about:
  home: https://github.com/jupyter/terminado
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Terminals served by tornado websockets
  description: |
    Terminado is a Tornado websocket backend for the term.js Javascript
    terminal emulator library.
  doc_url: http://terminado.readthedocs.org/en/latest/
  doc_source_url: https://github.com/takluyver/terminado/blob/master/doc/index.rst
  dev_url: https://github.com/takluyver/terminado

extra:
  recipe-maintainers:
    - blink1073
    - pelson
    - takluyver
    - ocefpaf
